/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as DetailFeaturedImport } from "./routes/_detail/featured";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const DetailFeaturedRoute = DetailFeaturedImport.update({
  id: "/_detail/featured",
  path: "/featured",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_detail/featured": {
      id: "/_detail/featured";
      path: "/featured";
      fullPath: "/featured";
      preLoaderRoute: typeof DetailFeaturedImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/featured": typeof DetailFeaturedRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/featured": typeof DetailFeaturedRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_detail/featured": typeof DetailFeaturedRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/featured";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/featured";
  id: "__root__" | "/" | "/_detail/featured";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DetailFeaturedRoute: typeof DetailFeaturedRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailFeaturedRoute: DetailFeaturedRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_detail/featured"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_detail/featured": {
      "filePath": "_detail/featured.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
